export interface Task {
    task_id: Number,
    user_id: Number,
    task_name: string,
    task_title: string,
    task_description: string,
    task_status: Number,
    task_hours: Number,
    task_planned_start_date: Date,
    task_planned_end_date: Date,
    task_actual_start_date: Date,
    task_actual_end_date: Date,
    task_notes: string,
    created_by: string,
    created_at: Date,
    updated_by: string,
    updated_at: Date,
    deleted_by: string,
    deleted_at: Date,
}